name: Rerun Job
on: [push]

jobs: 
  rerun-test: 
    runs-on: ubuntu-latest 
  steps: 
    - name: rerun CircleCI
      run: |
        curl -u $CIRCLE_API_USER_TOKEN: \
        -d build_parameters[CIRCLE_JOB]=test \
        https://circleci.com/api/v1.1/project/github/$GITHUB_REPOSITORY/tree/$GITHUB_HEAD_REF 
